  
name: Build Archive

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Install Utilities
      run: |
        brew install automake
        brew install libtool
    - name: Install
      run: |
        pod repo update
        pod install
    - name: Build
      run: xcodebuild -workspace mapcache-ios.xcworkspace -scheme mapcache-ios -allowProvisioningUpdates -configuration AppStoreDistribution archive -archivePath buildArchive/MapCache.xcarchive CODE_SIGNING_ALLOWED=NO
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: MapCache.xcarchive
        path: buildArchive/MapCache.xcarchive
